### ISSUE TITLE
Problem running edge and backend

### ISSUE THREAD

**Issue by Facj** [OpenEMS/openems#1024]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Bug description or desired functionality.
I have problems running OpenEMS edge and backend.
They do start and I am able to access them on Apache Felix but they do not connect to the UI.
I have searched in the log and I have not found anything about the websocket connection.
The error trace suggests that the problem may be related to Bndtools but I do not know how to solve it. I am using Bndtools 4.3.1 REL.
The error trace is quite long so I am attaching it in a text file.
[edge-error.txt](https://github.com/OpenEMS/openems/files/3944381/edge-error.txt)

**Comment by sfeilmeier** [comment]
Thank you for reporting. I committed a fix. Can you please test if it works for you?

Regards,
Stefan

**Comment by Facj** [comment]
Yes, it does work now.
Thank you!
