### ISSUE TITLE
There are error for launching UI (angluar.js) on 2020 version

### ISSUE THREAD

**Issue by ganadara135** [OpenEMS/openems#1042]
### Bug Report or Feature Request (mark with an `x`)
```
- [ X] bug report -> please search issues before submitting
- [ X] feature request
```

### Bug description or desired functionality.

This is the screenshot of bug report.
<img width="904" alt="스크린샷 2020-01-29 17 41 09" src="https://user-images.githubusercontent.com/24896007/73340735-a2c10680-42be-11ea-9a5a-c0ade84144f7.png">

error message : Cannot find module 'util'   in app/shared/pickdate/pickdate.component.ts

**Comment by fabianfnc** [comment]
this is a problem with the UI dependencies
has been fixed with commit #65a8605

get the newest version of develop/ type npm install
