### ISSUE TITLE
FEMS REST API not working

### ISSUE THREAD

**Issue by dnlGrande** [OpenEMS/openems#1043]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

**Comment by sfeilmeier** [comment]
Hello,

this project is about the open source project OpenEMS; FEMS (FENECON Energy Management System) is a product based on OpenEMS. 

If you need support with FEMS, please contact the FENECON service: https://www1.fenecon.de/kontakt/. To properly help you, the service will need more information like

- What is your FEMS number? (e.g. "fems1234")
- What exactly is not working?

Regards,
Stefan
