### ISSUE TITLE
ChannelSingleThreshold: StateMachine Channel is never set

### ISSUE THREAD

**Issue by sfeilmeier** [OpenEMS/openems#1070]
See:
https://github.com/OpenEMS/openems/blob/8d75206570605a36b04c60bea205e40a62b7ea8d/io.openems.edge.controller.io.channelsinglethreshold/src/io/openems/edge/controller/io/channelsinglethreshold/ChannelSingleThreshold.java#L39

This makes it very hard to debug using Grafana.

**Comment by venu-sagar** [comment]
Removed in #1077 .
