### ISSUE TITLE
SingleChannelThresholdController-Widget: "Change Failed [object Object]"

### ISSUE THREAD

**Issue by sfeilmeier** [OpenEMS/openems#1072]
On Error it shows the message "Change Failed [object Object]". The problem is in this line:
https://github.com/OpenEMS/openems/blob/c1dfdc619ea6ef39b867d7e2a06909fbfeafdd82/ui/src/app/edge/live/singlethreshold/modal/modal.component.ts#L152
"reason" is a object and needs to be formatted properly.

**Comment by fabianfnc** [comment]
will be fixed with #1071
