### ISSUE TITLE
UI shows off grid on a system without an ESS

### ISSUE THREAD

**Issue by clehne** [OpenEMS/openems#1261]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Bug description or desired functionality.
When opening OpenEMS UI Edge with latest development version (2020-10-21) on a system without any ESS the _offgrid.png_ is shown inside the energymonitor. Also the "Netz" component says: "Keine Netzverbindung!".

As far as I understand the icon depends on the __sum/GridMode_ channel and this channel is feed by ESS or ESS depending controllers. 
My system without ESS or ESS controllers shows offgrid all the time.

**Comment by sfeilmeier** [comment]
This is solved by #1748:

https://github.com/OpenEMS/openems/blob/c23532458c4853ef878af1320982a8616586c723/io.openems.edge.ess.api/src/io/openems/edge/ess/api/CalculateGridMode.java#L32-L34

Before this logic would have returned `GridMode.OFF_GRID` if there was no ESS.
