### ISSUE TITLE
ion-icon "contact-outline" doesn't exist

### ISSUE THREAD

**Issue by ahummelsberger** [OpenEMS/openems#1310]
https://github.com/OpenEMS/openems/blob/795ccec9a101cf9d024c1943a5f8c1a0b7017f0b/ui/src/app/index/index.component.html#L10

The ion-icon "contact-outline" doesn't exist.
Maybe it's a typo and should say "contract-outline".
My suggestion would be to use "person-outline" as it appears in the login window.

**Comment by fabianfnc** [comment]
Danke dir.
Werde ich mich drum kümmern.

**Comment by fabianfnc** [comment]
Wird mit https://github.com/OpenEMS/openems/pull/1311 gefixt.
