### ISSUE TITLE
[API] Insert Unit into channel output

### ISSUE THREAD

**Issue by martingruening** [OpenEMS/openems#1348]
Feature Request:
When reading a channel through the REST API also provide the unit of the channel.

Example - instead of
```
{
    "value": 457,
    "type": "integer",
    "writable": false
}
```

send
```
{
    "value": 457,
    "unit": "W",
    "type": "integer",
    "writable": false
}
```

**Comment by martingruening** [comment]
You can assign this to me. Done the easy modfication already. PR will follow bundled with other improvements in RestHandler.

**Comment by sfeilmeier** [comment]
A quick thought on this: if I would implement it, I would try to reuse the Channel representation in `EdgeConfig`. EdgeConfig is generally used to represent the entire configuration of an OpenEMS Edge and is used in OpenEMS UI to build the interface. See:

https://github.com/OpenEMS/openems/blob/develop/io.openems.common/src/io/openems/common/types/EdgeConfig.java#L236

**Comment by martingruening** [comment]
Good suggestion. Will do that. Shall I keep the existing "writable" property in the API code? This would make sure that we don't break code depending on the API, but then the writable property seems to be redundant with the "accessMode" property of the config.

**Comment by sfeilmeier** [comment]
I believe dropping the "writable" property is ok.
