### ISSUE TITLE
Documentation: Update Request

### ISSUE THREAD

**Issue by zoernert** [OpenEMS/openems#1484]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X ] feature request
```

### Bug description or desired functionality.
Update list of Board Members and members at https://github.com/OpenEMS/openems/blob/7ef5e337d13cd6539d665476308c0d5af60b1135/doc/modules/ROOT/pages/openems_as.adoc#vorstand

**Comment by sfeilmeier** [comment]
The information on OpenEMS Association was moved to https://openems.io/association/
