### ISSUE TITLE
NPE in AbstractMetadata.setInitialized creating instance of DummyMetadata

### ISSUE THREAD

**Issue by benhamidene** [OpenEMS/openems#1823]
- [x] Bug report 
- [ ] Feature Request
### Description
EventAdmin not injected in constructor
The creation of a DummyMetaData component is not possible, it throws a NPE , as the firing of an Event in setInitialized needs an injected instance of the EventAdmin (using @Reference)
But The injection does not occur in the constructor

```
	protected void setInitialized() {
		this.isInitialized.set(true);
	        EventBuilder.post(getEventAdmin(), Events.AFTER_IS_INITIALIZED);
	}
```
getEventAdmin() returns null

### Desired functionality.

So we need a better place to fire the Event Events.AFTER_IS_INITIALIZED
May be in activate() ?

**Comment by sfeilmeier** [comment]
Thanks for reporting. The issue should be fixed in #1824.
