### ISSUE TITLE
Feature Request; Smart-me meter

### ISSUE THREAD

**Issue by hansenelectric** [OpenEMS/openems#1925]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Bug description or desired functionality.

I would like to have the Smart-me Kamstrup Module added as a meter (production and grid meter). The Kamstrup meter is the most common utility meter in Denmark and with this device it's possible to get real-time data out of the utility meter. I would recommend to have it communicating via Modbus-TCP as this is faster than the API. I hope that you'll consider this feature request.

-->
https://web.smart-me.com/en/project/kamstrup-module/
https://doc.smart-me.com/cloud/modbus-tcp

**Comment by sfeilmeier** [comment]
@hansenelectric: We try to move all discussions to the OpenEMS Community (https://community.openems.io/), to have them in one central place. Please feel free to open a thread there.

It's quite easy to implement a meter in OpenEMS Edge via Modbus/TCP, if you have physical access to it. I do not have access and it's also not on our roadmap at FENECON, but we'll support you in the community if you plan to implement it.
