### ISSUE TITLE
Feature Request; Elspotprices for the Nordics

### ISSUE THREAD

**Issue by hansenelectric** [OpenEMS/openems#1926]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Bug description or desired functionality.

I would like to have the Day ahead spotprices in DK and neighboring countries implemented like the Tibber, aWattar, Stromdao functionality. It should however also be possible to enter a variable DistributionSystemOperator costs on top, which in Denmark is different between summer and winter (is regulated every year) and the operating hour, eg. [in DKK/kWh]
Winter tarif (oct-mar);
low load (24-06); 0,2126
high load (6-17 +21-24); 0,6379
Peak load (17-21); 1,9135

Summer tarif (apr-sep)
low load (24-06); 0,2126
high load (6-17 +21-24); 0,3189
Peak load (17-21); 0,8291

-->
https://www.energidataservice.dk/tso-electricity/Elspotprices
https://radiuselnet.dk/elnetkunder/tariffer-og-netabonnement/prisaendringer/

**Comment by hydroid7** [comment]
Hi,
thank you for the feature request. Can you please open a thread in the OpenEMS Community to discuss about your idea?
Best

**Comment by hansenelectric** [comment]
Hi
For sure. The thread is here; https://community.openems.io/t/feature-request-elspotprices-for-the-nordics-1926/1466

**Comment by hydroid7** [comment]
Closing this here because of community.
