### ISSUE TITLE
Calculate and show CO2 emissions savings

### ISSUE THREAD

**Issue by benzman81** [OpenEMS/openems#1931]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ x ] feature request
```

### Bug description or desired functionality.
It would be awesome to show the CO2 emissions savings in the live view and the history. Optimal would be an additonal setting to set the amount of saved CO2 per kwh.
Other systems already show this information, my e scooter too, and it is a really good feeling to see how much you do to save the environment.

**Comment by sfeilmeier** [comment]
@benzman81: We try to move all discussions to the OpenEMS Community (https://community.openems.io/), to have them in one central place. Please feel free to open a thread there.

Sorry for "just closing" all of your issues now. I am just cleaning up.
