### ISSUE TITLE
Show saved costs

### ISSUE THREAD

**Issue by benzman81** [OpenEMS/openems#1932]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ x ] feature request
```

### Bug description or desired functionality.
It would be great so the the saved costs in live and history view. Also a setting for your current price per kwh would be required to customize.
Other systems already show this information.

**Comment by sfeilmeier** [comment]
@benzman81: We try to move all discussions to the OpenEMS Community (https://community.openems.io/), to have them in one central place. Please feel free to open a thread there.

Sorry for "just closing" all of your issues now. I am just cleaning up.

"Prices" are something we heavily work on with "time-of-use" prices (Tibber, aWATTar, Corrently, RabotCharge, etc.). Maybe support for a static price will also come in that process.
