### ISSUE TITLE
Show how long battery power will last

### ISSUE THREAD

**Issue by benzman81** [OpenEMS/openems#1934]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ x ] feature request
```

### Bug description or desired functionality.
Would be awesome to see a prediction how long the battery power will last. This can either be simple by alwas taking the current consumtion into account or a bit smater by also takink the historical consumption into account. Even smarter ;-) would be to include the predicted solar power of the the next hours/days.
The simple implementation would be a great start.

**Comment by sfeilmeier** [comment]
Hi. We (FENECON) do not currently plan to implement this. Techically the feature would be similar to what is already implemented for the Grid-Optimized-Charge-Controller. The Controller uses predictions for Consumption and Production and visualizes the planned State-of-Charge of the battery:

![grafik](https://user-images.githubusercontent.com/3515268/192248945-aa33db8d-a661-4325-b650-90e838a7664d.png)

See:
- https://github.com/OpenEMS/openems/tree/develop/ui/src/app/edge/live/Controller/Ess/GridOptimizedCharge
- https://github.com/OpenEMS/openems/tree/develop/io.openems.edge.controller.ess.gridoptimizedcharge
- https://fenecon.de/produkte/fems/fems-app-netzdienliche-beladung/

**Comment by sfeilmeier** [comment]
@benzman81: We try to move all discussions to the OpenEMS Community (https://community.openems.io/), to have them in one central place. Please feel free to open a thread there.

Sorry for "just closing" all of your issues now. I am just cleaning up.

In fact this is also something we look into with the development of Time-of-Use algorithms. See this screenshot: https://openems.io/2023/12/04/mehr-freiheit-in-der-nutzung-dynamischer-stromtarife/
