### ISSUE TITLE
Grid optimized charge setting per time of year

### ISSUE THREAD

**Issue by benzman81** [OpenEMS/openems#1936]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ x ] feature request
```

### Bug description or desired functionality.
The grid optimized charging is a great feature. Using Fenecon since august 2022, I now noticed, that I would like to have different settings per time of year. For example, I would use the "high risk" setting during summer as it will probably fully charge my battery anyway, at least the next day, but would like to use the "low risk" setting  or even turnig it off in autuum/winter, as full charge has top most priority in this time of year.
For now, I did it manually a couple of weeks ago and are more happy with the "low risk" setting as of now. But since manually switching is always something to remind you of it would be nice if you can schedule it.

Side note: Maybe I am just not to familiar with the logic behind the grid optimized charging. But at least I noticed a difference between "high risk" setting and "low risk" setting during bad weather.

**Comment by sfeilmeier** [comment]
@benzman81: We try to move all discussions to the OpenEMS Community (https://community.openems.io/), to have them in one central place. Please feel free to open a thread there.

Sorry for "just closing" all of your issues now. I am just cleaning up.

Technically there is a way to "automate" the risk mode. You would have to simulate a UI and send the same JSON-RPC request as in here: https://github.com/OpenEMS/openems/blob/develop/ui/src/app/edge/live/Controller/Ess/GridOptimizedCharge/modal/modal.ts. We do not document this feature, as we are currently refactoring this and would break the API.
