### ISSUE TITLE
Add notes to phases in current consumption view

### ISSUE THREAD

**Issue by benzman81** [OpenEMS/openems#1957]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ x ] feature request
```

### Bug description or desired functionality.
Would be great if we could add some notes to each phase in the overview of current consumtion. My idea is, that I can write down the connected devices. This way I would have an overview which phase is using how much power and what devices may be the cause for it.

**Comment by clehne** [comment]
I don't think there is a need for this. Not sure if you have seen it. But you can get that information also, if you go to -> history -> consumption. There you have an options button in the upper left corner. Open it and switch "Phases" to on. Then your view changes and you can simple map the consumption of any device against the consumption of each Phase L1,L2 or L3.

**Comment by benzman81** [comment]
@clehne first, thanks for the hint with the options. Since there is mostly the hamburger menu I did not recognize this.
To clarify, my need is to have a view on the current consumtion per phase and see directly which device in my house are connected to it. Today, I have a document on my phone with a mapping of deviced to phase where I always have to look up and check. That is, why a view like the following would be very convenient.

![feneconmockup](https://user-images.githubusercontent.com/14224592/198523455-d3c4121c-92b7-42fa-b87f-dabc67911dab.png)

In consumtion history this would be great, too.

**Comment by sfeilmeier** [comment]
@benzman81: We try to move all discussions to the OpenEMS Community (https://community.openems.io/), to have them in one central place. Please feel free to open a thread there.

Also if this is a feature request for a FENECON energy storage system (the colours look much like a FEMS), please get in touch with FENECON Service: https://fenecon.de/kontakt/
