### ISSUE TITLE
Historical total consumption per phase

### ISSUE THREAD

**Issue by benzman81** [OpenEMS/openems#1965]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ X ] feature request
```

### Bug description or desired functionality.
Currently you can only see the historical total consumption of a defined time, but you cannot see the total per phase. Since I would like to know which of my phases is consuming the most to identify devices with a high consumption, I would like to be able to see the total per phase in a defined time, too.

**Comment by sfeilmeier** [comment]
@benzman81: We try to move all discussions to the OpenEMS Community (https://community.openems.io/), to have them in one central place. Please feel free to open a thread there.
