### ISSUE TITLE
TibberImpl.java is using obsolete APIv1

### ISSUE THREAD

**Issue by sputniki** [OpenEMS/openems#2049]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Bug description or desired functionality.

io.openems.edge.timeofusetariff.tibber/src/io/openems/edge/timeofusetariff/tibber/TibberImpl.java uses Tibber-APIv1 which has been replaced end of 2022 by GraphQL implementation: https://developer.tibber.com/docs/overview#breaking-websocket-change

So the API call might fail and the controller won't work properly

**Comment by sfeilmeier** [comment]
Thanks @sputniki.

According to the docs you linked, the API endpoint we are using is still valid.
- https://developer.tibber.com/docs/guides/calling-api
- https://github.com/OpenEMS/openems/blob/develop/io.openems.edge.timeofusetariff.tibber/src/io/openems/edge/timeofusetariff/tibber/TibberImpl.java

The 'breaking change' is only for subscribtions via WebSocket, which we are not using. 

If I am not wrong, there is nothing we need to change at the moment.
