### ISSUE TITLE
how modbus request data and parse data?

### ISSUE THREAD

**Issue by stly** [OpenEMS/openems#2169]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Bug description or desired functionality.

@sfeilmeier hi 
this system can send the data request through modbus tcp and receive the response data, then parse the data, and store it in the database.
I would like to know the specific details of this process, especially how the data is parsed?
I've read the docs and I'm still confused about the parsing part。
thanks a lot @sfeilmeier

**Comment by hydroid7** [comment]
Hi,
is there a specific task you want to achieve? There are a lot of examples how to use the Modbus parser. 

OpenEMS uses `j2mod` under the hood for communicating with modbus devices. You can find a simple example on how to use the OpenEMS modbus API in the implementation of the [Hypercharger](https://github.com/OpenEMS/openems/blob/main/io.openems.edge.evcs.alpitronic.hypercharger/src/io/openems/edge/evcs/hypercharger/HyperchargerImpl.java).

Besides that feel free to sign up to the [OpenEMS Community](https://community.openems.io/) discussion forum where you can get help and advice on custom use cases and implementations.

Best
