### ISSUE TITLE
Send E-Mail on warning/error

### ISSUE THREAD

**Issue by sfeilmeier** [OpenEMS/openems#22]
From femsserver created by [sfeilmeier](https://github.com/sfeilmeier) : OpenEMS/femsserver#4  

### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Desired functionality.

When a warning or error is happening, send an email to fems@fenecon.de.

**Comment by ebakir** [comment]
First:
capture exceptions centralized
