### ISSUE TITLE
openEMS docs: missing page - Backend Architecture 

### ISSUE THREAD

**Issue by Byonnem** [OpenEMS/openems#2206]
- [#] bug report -> please search issues before submitting
- [ ] feature request

https://openems.github.io/openems.io/openems/latest/backend/architecture.html is an empty page. I also cannot find what is supposed to be there, so it might be a feature request to fill the page instead of a bug? :)

**Comment by sfeilmeier** [comment]
It's in fact a feature request ;-)

I do recommend OpenEMS Community (https://community.openems.io/), as a lot of questions have already been answered there.
