### ISSUE TITLE
why we were unable to open UI in http://localhost:8085/ port and unable get backend UI when running backend dev in cloud server. Please suggest any to get backen UI with edge displaying

### ISSUE THREAD

**Issue by vnvasireddy** [OpenEMS/openems#2229]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
```

**Comment by sebastianasen** [comment]
Hi @vnvasireddy,

it is more common to ask questions like this on the community forum.
https://community.openems.io

It is easier to find questions that have already been answered and more people are informed when new questions arise

Best regards,
Sebastian
