### ISSUE TITLE
FC4 Register(s) Read Once

### ISSUE THREAD

**Issue by Sn0w3y** [OpenEMS/openems#2281]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X ] feature request
```

Desired functionality:

Read FC4 Input Registers once in ModbusUtils.

Usecase same as Holding Registers reading but for FC4 Registers:

	public static <T> CompletableFuture<T> readElementOnceFC4(ModbusProtocol modbusProtocol,
			AbstractModbusElement<T> element, boolean tryAgainOnError) throws OpenemsException {

		final var result = new CompletableFuture<T>();

		final Task task = new FC4ReadInputRegistersTask(element.getStartAddress(), Priority.HIGH, element);
		modbusProtocol.addTask(task);

		element.onUpdateCallback(value -> {
			if (value == null) {
				if (tryAgainOnError) {
					return;
				}
				result.complete(null);
			}

			modbusProtocol.removeTask(task);
			result.complete(value);
		});

		return result;
	}

	public static <T> CompletableFuture<List<T>> readElementsOnceFC4(ModbusProtocol modbusProtocol,
			AbstractModbusElement<T>[] elements, boolean tryAgainOnError) throws OpenemsException {

		if (elements.length == 0) {
			return CompletableFuture.completedFuture(Collections.emptyList());
		}

		final var result = new CompletableFuture<List<T>>();
		final Task task = new FC4ReadInputRegistersTask(elements[0].getStartAddress(), Priority.HIGH, elements);
		modbusProtocol.addTask(task);

		final var subResults = new ArrayList<CompletableFuture<T>>();
		{
			var subResult = new CompletableFuture<T>();
			subResults.add(subResult);
			elements[0].onUpdateCallback(value -> {
				if (value == null) {
					if (tryAgainOnError) {
						return;
					} else {
						result.complete(null);
					}
				}

				modbusProtocol.removeTask(task);
				subResult.complete(value);
			});
		}

		for (var i = 1; i < elements.length; i++) {
			var subResult = new CompletableFuture<T>();
			subResults.add(subResult);
			elements[i].onUpdateCallback(value -> {
				modbusProtocol.removeTask(task);
				subResult.complete(value);
			});
		}

		CompletableFuture //
				.allOf(subResults.toArray(new CompletableFuture[subResults.size()])) //
				.thenAccept(ignored -> result.complete(//
						subResults.stream() //
								.map(CompletableFuture::join) //
								.toList()));

		return result;
	}

**Comment by sfeilmeier** [comment]
Hi @Sn0w3y,

Could you try and make this a pull-request, please? I can recommend https://desktop.github.com/, it really simplifies the process.

Thanks!
