### ISSUE TITLE
[Bug] Janitza Meter incorrect modbus definition for energy values

### ISSUE THREAD

**Issue by jpdark** [OpenEMS/openems#2312]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Bug description or desired functionality.

The Janitza UMG96RM-E Meter, has wrongly implemented the consumption and production energy.
In the definition of the Modbus protocol, the two are switched.
Below is a screenshot of the relevant modbus entries in the documentation for the meter.
The relevant code section (including invert conditional) is also added for comparison.

<img width="643" alt="Screenshot_2023-08-10_at_12_01_58" src="https://github.com/OpenEMS/openems/assets/8161297/12acacd1-669b-4c8b-b399-f2500eca760b">

```java
if (this.invert) {
	modbusProtocol.addTask(new FC3ReadRegistersTask(19068, Priority.LOW, //
	        m(ElectricityMeter.ChannelId.ACTIVE_CONSUMPTION_ENERGY, new FloatDoublewordElement(19068)),
	        new DummyRegisterElement(19070, 19075),
	        m(ElectricityMeter.ChannelId.ACTIVE_PRODUCTION_ENERGY, new FloatDoublewordElement(19076))));
} else {
	modbusProtocol.addTask(new FC3ReadRegistersTask(19068, Priority.LOW, //
	        m(ElectricityMeter.ChannelId.ACTIVE_PRODUCTION_ENERGY, new FloatDoublewordElement(19068)),
	        new DummyRegisterElement(19070, 19075),
	        m(ElectricityMeter.ChannelId.ACTIVE_CONSUMPTION_ENERGY, new FloatDoublewordElement(19076))));
}
```

**How to fix**
Since this implementation may already be used in many instances of the OpenEMS software, breaking changes are to be avoided if possible.

~~1. Simply switch the code blocks in the invert statement~~ breaking change.
2. Add flag to the `Config` of the current Janitza meter implementation, triggering a new code path with the correct implementation. The default option should still follow the current code path. An additional (deprecation) warning could be added for users and introduce a full breaking-change in a future release, clearly planned and communicated to the community.

For now, we have simply made a copy of the implementation for our own use. However, we do feel that planning a (breaking) change to rectify this mistake in the future would be preferable.

Maybe there is a better path; please share your thoughts.

**Comment by sfeilmeier** [comment]
@jpdark: Thanks for bringing this up and analyzing in depth. The idea is, that:
- positve `ActivePower` values relate with `ActiveProductionEnergy`
- negative `ActivePower` values relate with `ActiveConsumptionEnergy`
(I know know, that this terminology was a bad choice back then, but it is what it is...)

If I understand you correctly, this relation is not the case with the Janitza Meter right now. In that case we should change it, no matter if it is a breaking change or not.

I am trying to move all discussions to OpenEMS Community (https://community.openems.io/), so I'll close this here. You may still relate to this issue for now. Thanks.
