### ISSUE TITLE
Energy calculation instead of modbus registers

### ISSUE THREAD

**Issue by tsicking** [OpenEMS/openems#2441]
https://github.com/OpenEMS/openems/blob/887f076baa106e9671fddc6e18e47b4e08b3ffc9/io.openems.edge.meter.microcare.sdm630/src/io/openems/edge/meter/microcare/sdm630/MeterMicrocareSdm630Impl.java#L223C17-L223C17

Since a recent FEMS-backport, the meter microcare SDM 630 uses `CalculateEnergyFromPower` instead of reading the values via modbus. What is the reason for this? I would think that reading values from the meter is more accurate, and the calculation is only used when there are no values from the device.

**Comment by sfeilmeier** [comment]
We are generally switching to self-calculating energy for all devices. We found that the error is rather small, but we have a lot of benefits, e.g. for the very first reading to start at "0 Wh" (and consequently avoiding high consumption/production on the day of setup) and when a meter, inverter, etc. gets exchanged later.

Of course you are right, that the interal calculation should always be even better. We had started some discussions in the past on how to combine both approaches. If this is a topic for you, maybe we can join forces.
