### ISSUE TITLE
.vscode/settings is forcing format when saving, but editor.defaultFormatter is not specified.

### ISSUE THREAD

**Issue by miettal** [OpenEMS/openems#2447]
if a vscode user use another formatter (like prettier) as editor.defaultFormatter in user-side-config, the development will be difficult. because workspace-side-config force to run format and user-side-config formatter try to apply different styling policy.

I think, in case of  forcing format when saving, specifiing workspace policy formatter as editor.defaultFormatter is better.

https://github.com/OpenEMS/openems/blob/edfe1f0ac47a70f25c7c6456289d58344b6c3ab7/ui/.vscode/settings.json#L3

**Comment by sfeilmeier** [comment]
@lukasrgr: Should we add `editor.defaultFormatter`?

**Comment by miettal** [comment]
now `.eslintrc` is in project directory(/ui) and developper following eslint rule, therefore I think "editor.defaultFormatter": "dbaeumer.vscode-eslint" is suitable.

**Comment by lukasrgr** [comment]
@venu-sagar i think i saw this in your config

**Comment by miettal** [comment]
I tried to configure it in my local dev environment. it's working. how about this?
https://github.com/girasolenergy/openems-fork/commit/6931885b740c061f2af0218239afbadb1d069d5d

// if this is ok, I can make a PR.

![test](https://github.com/OpenEMS/openems/assets/118803/e28e7851-579b-4e98-91b7-265b2a195538)
