### ISSUE TITLE
aWattar Country AUT - GER

### ISSUE THREAD

**Issue by cf99** [OpenEMS/openems#2469]
- [x ] feature request

Unfortunately the missmatch of cost between austria and germany is still not considerd.
I just had a houerly price deviation of 300% (okay that sounds huge, 1.4c€ to ~4.2c€) but still it is annoying. because there is just a change in the domain (.de or .at) required...

https://www.awattar.de/services/charts/hourly
https://www.awattar.at/services/charts/hourly

**Comment by venu-sagar** [comment]
@cf99 Thank you for raising this issue. 

We primarily focused on the German market. I will work on adding a feature that lets you choose between the German and Austrian markets for pricing. This way, you can easily view the right prices for your needs. I'll be submitting the pull request (PR) shortly to make this option available.

In the meantime, you can check prices easily using our ENTSO-E feature. This tool is like a general API for getting day-ahead prices in European power grids. It taps into the ENTSO-E transparency platform, making it a simple and effective way to access pricing information. Feel free to use it while we're working on updates for the Awattar's Austrian market integration.

[io.openems.edge.timeofusetariff.entsoe](https://github.com/OpenEMS/openems/tree/develop/io.openems.edge.timeofusetariff.entsoe)

It retrives prices from ENTSO-E platform. You have to create an account at https://transparency.entsoe.eu/ to get an security token and In the configuration just select the option Austria in the "Bidding Zone".

Let me know if you find any issues while initializing ENTSO-E provider.

**Comment by Sn0w3y** [comment]
[awattar.zip](https://github.com/OpenEMS/openems/files/13932284/awattar.zip)

fixed it in here - maybe Review and Push it :)

**Comment by cf99** [comment]
i am sorry i can review it (I have now idea how to code).
Who will/ can do this?

**Comment by Sn0w3y** [comment]
@venu-sagar
