### ISSUE TITLE
kWh values

### ISSUE THREAD

**Issue by ebakir** [OpenEMS/openems#32]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x ] feature request
```

### Desired functionality.

In history view: Show kWh values for selected period for production, consumption, ... Make it foldable, to show data also per phase and per device.

**Comment by ebakir** [comment]
Before:
create a statement which fills empty fields in the database with values if the device was online

**Comment by sfeilmeier** [comment]
Show also total charged/discharged energy and number of full cycles of the battery
