### ISSUE TITLE
Continuously write all values to influxdb

### ISSUE THREAD

**Issue by sfeilmeier** [OpenEMS/openems#34]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Bug description or desired functionality.

OpenEMS is only sending changes to the server. In order to ease graphical display, the server should continuously write all current values to the database.

**Comment by ebakir** [comment]
Closed by commit fa027b05f61b47f4b411facca4c1f24c943f86da
