### ISSUE TITLE
access level for configChannels

### ISSUE THREAD

**Issue by MatthiasRossmann** [OpenEMS/openems#38]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
```

### Bug description or desired functionality.
provide access to ConfigChannels for different user groups.
UI: display only configConfigChannels if user has right
Edge: check if user has right to set ConfigChannel

**Comment by sfeilmeier** [comment]
Follow up: #40
