### ISSUE TITLE
Config/UI: send meta-data directly with config values

### ISSUE THREAD

**Issue by sfeilmeier** [OpenEMS/openems#41]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Bug description or desired functionality.

UI code is clattered with finding meta information about things/channels/... This data should be combined with the values on server side already. Suggested implementation:
{
    title: '...', -> from meta
    name: '...',
    value: { ... }
}
Because we are using a FormGroup always then, "forminput.component.html" can be simplified.

**Comment by ebakir** [comment]
depending on
https://github.com/OpenEMS/openems/issues/55
