### ISSUE TITLE
cpu usage increases by runtime

### ISSUE THREAD

**Issue by MatthiasRossmann** [OpenEMS/openems#5]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.
run openems
top -> openems has cpu usage about 15%
run openems for about two weeks
top -> openems has cpu usage about 90%

**Comment by sfeilmeier** [comment]
Should be fixed with commit update of websocket api https://github.com/OpenEMS/openems/commit/2bb234a3b022e91d3ec01688dfbe5d6fb0603d3f
