### ISSUE TITLE
connection-problems with local FEMS web ui on Firefox and Edge

### ISSUE THREAD

**Issue by theMomax** [OpenEMS/openems#63]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Bug description or desired functionality.

Today (03/15/18) a problem occurred concerning the FEMS web ui. This seems to be related to yesterday's update to tag 2018.3.0 (05282ed9397b3bae1697dbbcdc05fad78801656b). I wonder if this update was planned since the tag wasn't released yet.

#### Technical Description:
 * the UI fails to connect (messages: "Trying to reconnect" and "Connecting"
 * the problem occurred on both Firefox and Edge on Windows 10 and 7, while there was no problem on Chrome (same operating systems) and Safari (macOS High Sierra)
 * the UI was accessed using the FEMS-device's local ip
 * the Grafana visualization (which is directly connected to the InfluxDB API) works on all devices however

#### Screenshots:

![a_fems](https://user-images.githubusercontent.com/21169289/37486835-015b4bba-2890-11e8-8c6b-c54bb190144c.PNG)

<img width="460" alt="fems" src="https://user-images.githubusercontent.com/21169289/37486767-c1ffcd38-288f-11e8-986e-18733c2b8789.png">

Unluckily I'm in lack of time right now, otherwise I'd try to fix this myself...

**Comment by sfeilmeier** [comment]
Hi Max,

thank you for the detailed bug report!

We were fighting with this issue a lot yesterday and solved it with commit 0823d6f7748e53d1face4829c2497042b5f1ea18. There seems to be a problem with the previously used 'rxjs-websockets' library, so we changed to rxjs' WebSocketSubject.

Regards,
Stefan
