### ISSUE TITLE
Compatibility with OpenJDK 11

### ISSUE THREAD

**Issue by sfeilmeier** [OpenEMS/openems#655]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Bug description or desired functionality.

Currently OpenEMS Edge seems to be incompatible with OpenJDK 11. See https://community.openems.io/t/bug-when-launching-openems/101/4 for details

**Comment by KyleMicrocare** [comment]
hopefully this will also mean compatibility with [Amazon Coretto](https://aws.amazon.com/corretto/) so we can run Backend instances via AWS
