### ISSUE TITLE
Error in connection establishment

### ISSUE THREAD

**Issue by PlotlyUser2** [OpenEMS/openems#79]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

Hi Stefan,

I've build the ui source with 

> 
ng build
> 

and serving the app with the basic configuration of the lighttpd webserver.
However, anytime I try to open the webpage I get this connection refused error:

![screenshot from 2018-08-14 21-34-11](https://user-images.githubusercontent.com/39842435/44114014-36d23488-a00a-11e8-8392-0f4176669a37.png)

What is going wrong here? Further, I've noticed that this issue was already reported, see #63...
PS: I'm on latest Ubuntu

**Comment by sfeilmeier** [comment]
Hi,

can you verify that the "Controller Api Websocket" is running? See https://github.com/OpenEMS/openems/blob/develop/doc/OpenEMS_EN.adoc#23-run-openems-edge-and-start-simulator, paragraph "viii". It needs to be reachable on "ws://localhost:8085".

**Comment by PlotlyUser2** [comment]
Yeah... that was a triple facepalm... I missed that option somehow... It's working

![image](https://user-images.githubusercontent.com/39842435/44115196-838f84d0-a00d-11e8-96b4-55b2a6100d7d.png)

**Comment by sfeilmeier** [comment]
Haha. I'm glad it's working. :laughing: :+1:
