### ISSUE TITLE
Overview of cumulated values

### ISSUE THREAD

**Issue by theMomax** [OpenEMS/openems#91]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Bug description or desired functionality.

It would be nice to have get information on cumulated data for different periods. E.g. daily/monthly/yearly charging and discharging values.

**Comment by sfeilmeier** [comment]
We are moving all discussions to the OpenEMS Community (https://community.openems.io/), to have them in one central place. Please feel free to open a thread there.

Getting cumulated data over periods is now possible using JSONRPC requests to Edge or Backend.
